name: Deploy to GitHub Packages
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}/src/main/resources

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip

      - name: Publish to GitHub Packages
        run: mvn deploy
